.golangci.yml
cmd/root_test.go
cmd/start.go
cmd/start_test.go
internal/httpproxy/http_proxy.go
internal/httpproxy/http_proxy_test.go

- Use Viper to bind all command flags so they can be set as environment variables.
- Standardize flag names

refactor: Cleaner configuration setup using Viper

---

internal/httpproxy/http_proxy.go
internal/token/gat_claims.go
internal/wsproxy/hijacker_test.go
internal/wsproxy/recorder.go
internal/wsproxy/recorder_test.go

- For each API request, create a logger with common log keys so all logging would include them
+ `request_id`
+ `method`
+ `url`
+ `remote_addr`
+ `user` object (from GAT's `user` claim)
- Use this logger in session recording so the recording log can be correlated to a user.
- Separate log keys under `request` key (for request information) and `response` key (for response information)
- Sample logs for `kubectl auth`
```
{
"levelname": "info",
"ts": "2025-05-27T22:07:32.902Z",
"logger": "k8sgateway",
"caller": "http/server.go:2822",
"message": "API request",
"version": "0.0.1",
"request_id": "7d3bbfcc-42fe-4414-b806-017c83c5fb05",
"method": "POST",
"url": "/apis/authentication.k8s.io/v1/selfsubjectreviews",
"remote_addr": "10.16.1.4:59194",
"user": {
"id": "VXNlcjoxNTQ4NDQ1",
"username": …
```

feat: Better structured logging

---

deploy/gateway/templates/_helpers.tpl
deploy/gateway/tests/__snapshot__/NOTES_test.yaml.snap
deploy/gateway/tests/__snapshot__/snapshot_test.yaml.snap

Fix the default `host` value to "twingate.com" in Helm chart

fix: Fix the default `host` value to `twingate.com` in Helm chart

---

.golangci.yml
internal/connect/connect.go
internal/connect/connect_test.go
internal/httpproxy/http_proxy.go
internal/httpproxy/http_proxy_test.go

- parse `X-Connection-ID` from CONNECT and store as conn metadata
- use connection ID for logging
- add user info to logging if available in listener `Accept()`
example logs:
```
{"levelname":"error","ts":"2025-05-31T23:45:45.544-0700","logger":"k8sgateway","caller":"httpproxy/http_proxy.go:394","message":"failed to serve request: missing identity header in CONNECT failed to parse bearer token : Bearer","version":"0.0.1","conn_id":"467e6404-58ab-4a34-8534-534a9f16d228"}
```
```
{"levelname":"error","ts":"2025-05-31T23:47:06.328-0700","logger":"k8sgateway","caller":"httpproxy/http_proxy.go:394","message":"failed to serve request: failed to verify signature","version":"0.0.1","user":{"id":"VXNlcjoxNTQ4NDQ2","username":"sean@acme.com","groups":["Everyone"]},"conn_id":"e1aa3a08-1535-423a-9032- …
```

feat: connection id

---

.goreleaser.yaml
cmd/root_test.go
cmd/start.go
internal/connect/connect_test.go
internal/httpproxy/http_proxy.go
internal/httpproxy/http_proxy_test.go
internal/log/logger.go
internal/version/version.go

- Setup `ldflags` to receive the build metadata in Go code
- Use build version in log context
- Change logger name to `gateway` (default, for gateway issue) and `audit` (for auditing user activities) 
Sample logs from local build
```
{
"levelname": "info",
"ts": "2025-05-30T22:40:13.567-0700",
"logger": "gateway",
"caller": "cmd/start.go:28",
"message": "initializing Logger",
"version": "0.1.2-local+0069f57"
}
{
"levelname": "info",
"ts": "2025-05-30T22:40:13.568-0700",
"logger": "gateway",
"caller": "cobra@v1.9.1/command.go:1015",
"message": "Gateway start called: map[debug:false host:twingate.com k8sapiserverca: k8sapiservertoken: network: port:8443 tlscert: tlskey:]",
"version": "0.1.2-local+0069f57"
}
```

feat: Logging improvements

---

internal/connect/connect.go
internal/connect/connect_test.go

Using `ecdsa.SignASN1` to simplify test code and remove unnecessary struct

chore: Using `ecdsa.SignASN1` to simplify test code

---

internal/httpproxy/http_proxy.go
internal/httpproxy/http_proxy_test.go

Skip auditing for the following operations
- `kubectl cp`
- `kubectl exec` with `tar` command (`kubectl cp` actually does this behind the scene)
- `kubectl logs`

feat: Skip auditing for certain operations

---

cmd/start.go
internal/httpproxy/http_proxy.go

Use client-go's `NewBearerAuthWithRefreshRoundTripper` transport to refresh the bearer token from the provided file (`/var/run/secrets/kubernetes.io/serviceaccount/token` for in-cluster deployment)

feat: Support bearer token refresh for in-cluster deployment

---

deploy/gateway/templates/NOTES.txt
deploy/gateway/tests/__snapshot__/NOTES_test.yaml.snap

- Update `NOTES.txt` installation instructions for `LoadBalancer` service type
Some Cloud providers (E.g. AWS) do not have the `ip` field in the `status.loadBalancer.ingress[0]` object.

chore: Update Helm installation instruction for `LoadBalancer` service type

---

internal/connect/connect_test.go
internal/httpproxy/http_proxy_test.go
internal/token/parser_test.go
internal/wsproxy/conn_test.go
internal/wsproxy/hijacker_test.go
internal/wsproxy/msg_test.go
test/integration/authentication_test.go

- Update unit test to use `testify/assert` and `testify/require`

refactor: Modernize tests to use `testify`

---

internal/httpproxy/http_proxy.go
internal/httpproxy/http_proxy_test.go

`Listener.Accept()` is blocking on `http.Server` main coroutine i.e. only one `CONNECT` message could be processed at a time. Move the logic handling `CONNECT` to `ProxyConn.Read()`

fix: Move `CONNECT` handling logic from `Listener.Accept()` to `ProxyConn.Read()`

---

internal/wsproxy/recorder.go
internal/wsproxy/recorder_test.go

This allows each session recording part is a valid Asciinema. End user should remove the header of subsequent parts when "stitching" the whole recording.

feat: Include Asciinema header in every session recording part

---

go.mod
internal/httpproxy/audit_middleware.go
internal/httpproxy/audit_middleware_test.go
internal/httpproxy/http_proxy.go
internal/httpproxy/http_proxy_test.go
test/integration/authentication_test.go

- For each API request, create 1 audit log (instead of 2) when the response is completed.
+ Add `requested_at` timestamp field
+ `request` field contains the request info e.g. `headers`
+ `response` field contains the response info e.g.g `status_code` and `headers`.
- No longer log the request and response's body
- This change would log all API requests, including requests that are upgraded to WebSocket streaming. Previously, if a request fails to upgrade to WebSocket streaming, we didn't log its response.
- Sample log
```json
{
"message": "API request complete",
"request_id": "767848ad-2dc4-4a4f-b685-fe98e8a1ecd1",
"requested_at": "2025-06-20T15:55:55.540-0700" 
"method": "GET",
"url": "/api/v1/namespaces/default/pods?limit=500",
"remote_addr": "10.16.0.3:36634",
"user": {
"id": …
```

feat: Improve audit log for API requests

---

internal/httpproxy/audit_middleware.go

Always re-panic error in audit middleware, including the expected `http.ErrAbortHandler` error so other middlewares or the `http.Server` can do their own cleanup.

fix: Always re-panic error in audit middleware

---

deploy/gateway/templates/deployment.yaml
deploy/gateway/templates/service.yaml
deploy/gateway/tests/deployment_test.yaml
deploy/gateway/tests/service_test.yaml
deploy/gateway/values.schema.json
deploy/gateway/values.yaml

- Support `NodePort` service type
- Support `extraEnvVars` in the deployment template

feat: Extend service and deployment templates in Helm Chart

---

.github/workflows/ci.yaml
.golangci.yml
cmd/start.go
internal/httpproxy/audit_middleware.go
internal/httpproxy/audit_middleware_test.go
internal/httpproxy/http_proxy.go
internal/httpproxy/http_proxy_test.go
internal/log/logger.go
internal/metrics/http_middleware_test.go
internal/token/gat_claims_test.go
internal/wsproxy/conn.go
internal/wsproxy/hijacker.go
internal/wsproxy/hijacker_test.go
internal/wsproxy/recorder.go
internal/wsproxy/recorder_test.go
test/fake/client.go
test/integration/authentication_test.go

- `golangci-lint@v2.2` added [`noinlineerr`](https://github.com/AlwxSin/noinlineerr), [`embeddedstructfieldcheck`](https://github.com/manuelarte/embeddedstructfieldcheck) and [`wsl_v5`](https://github.com/bombsimon/wsl) (see full [changelog](https://golangci-lint.run/product/changelog/#v220)), which causes `make lint` to fail locally. We did not see it in our CI because it is still using `golangci-lint@v2.1`.
- Fix `wsl_v5` lint error
- Fix `embeddedstructfieldcheck` lint error
- Disable `noinlineerr` to allow inline errors
- Fix `revive`'s `unhandled-error` rule lint error and ignore the rule for `bytes.Buffer.Write` function

chore: Upgrade `golangci-lint` to v2.2.1

---

test/integration/concurrent_users_test.go

Use `assert.Contains` instead of `assert.Equal` because `kubectl exec` might output warning message sporadically.

test: Fix flaky test due to sporadic warning message

---

test/integration/concurrent_users_test.go

https://github.com/Twingate/kubernetes-access-gateway/pull/61 didn't fix the flaky test because the ordering in the `assert.Contains` wasn't used correctly

test: Use `assert.Contains` correctly

---

internal/token/gat_claims.go
internal/token/gat_claims_test.go

Make GAT's `device` claim optional

fix: Make `device` claim optional in GAT

---

test/integration/concurrent_users_test.go
test/integration/testutil/kind.go

Fix flaky test due to warning message from `kubectl exec ... -- sleep 2` command

test: Fix flaky integration test

---

README.md

- Extract developers set up to its own Wiki page https://github.com/Twingate/kubernetes-access-gateway/wiki/Developers

chore: Simplify README to make Quick Start and Installation guides obvious

---

.github/workflows/ci.yaml
Caddyfile
README.md
cmd/start.go
internal/token/parser.go
test/fake/controller.go
test/integration/concurrent_users_test.go
test/integration/single_user_test.go

- Remove `fakeControllerURL` environment variable. 
- Rework integration setup to wire Gateway to fake Controller server running locally.
+ Fake controller runs at `http://localhost:8080`
+ Gateway would talk to fake Controller at `https://acme.test`
+ Use [Caddy reverse proxy](https://caddyserver.com/docs/quick-starts/reverse-proxy) to route `https://acme.test` to `http://localhost:8080`. Caddy would handle TLS cert generation.
+ Add `127.0.0.1 acme.test` entry to `/etc/hosts`
This setup has a limitation that Caddy expects fake Controller to run at port `8080` so only 1 fake Controller could run at any time. Hence, integration tests run sequentially.

fix: Remove fakeControllerURL env var

---

internal/wsproxy/recorder.go
internal/wsproxy/recorder_test.go
test/integration/testutil/assertions.go

Rename log fields from `asciinema` to `asciicast` because [`asciicast`](https://docs.asciinema.org/manual/asciicast/v2/#asciicast-v2) is the name of the file format. Asciiname refers to the software suite around this `asciicast` format.

feat: Rename asciinema log fields

---

internal/wsproxy/recorder.go
internal/wsproxy/recorder_test.go

- Remove unused `env` asciicast header

fix: Remove unused `env` asciicast header

---

internal/httpproxy/http_proxy.go

- Set 10-second timeouts in the authentication path during HTTP CONNECT request

feat: Set timeouts during CONNECT message for authentication

---

deploy/gateway/values.yaml

- The expression `max_over_time(...)` returns either `0` or `1`. Prometheus treat these two values as "truthy" when evaluating the rule. After adding `max_over_time(...) > 0`, it would filter the results, and the filtered results treated as "falsy".
- Update `TwingateGatewayHighAuthenticationFailures` alert to address an edge case. The edge case happens when the first request is an error after a cold start; the calculated error percentage would be 100%.

fix: Update broken alert

---

internal/httpproxy/http_proxy_test.go
test/data/data.go
test/e2e/e2e_test.go

- Update e2e test and `http_proxy` unit test to use `embed` directive instead of `os.ReadFile`

chore: Use `embed` directive in all tests

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.tool-versions
go.mod

- Upgrade to Go 1.25.0
- Upgrade golangci-lint to [2.4](https://github.com/golangci/golangci-lint/releases) which is needed to support new Go version

chore: Upgrade to Go 1.25.0 and golangci-lint to 2.4

---

deploy/gateway/tests/__snapshot__/configmap-grafana-dashboard_test.yaml.snap

- Fix `configmap-grafana-dashboard` snapshot test
Unfortunately, `helm-unittest@v1.0.0` is having a [known issue](https://github.com/helm-unittest/helm-unittest/issues/712) with `matchSnapshot`, that is why the `test-helm` CI did not fail in this [PR](https://github.com/Twingate/kubernetes-access-gateway/pull/104). I only found this issue locally because I was using an `helm-unittest` older version.

chore: Update helm unit test
